name: training_booking_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  firebase_database: ^10.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/govt-kerala-1-h6R.png
    - assets/images-1-TWy.png
    - assets/auto-group-dno3.png
    - assets/auto-group-n5sz.png
    - assets/rectangle-388-bg.png
    - assets/vector-qTX.png
    - assets/rectangle-389-bg-h8u.png
    - assets/vector-MkD.png
    - assets/vector-XGd.png
    - assets/vector-pC1.png
    - assets/rectangle-389-bg-uAZ.png
    - assets/vector-JVw.png
    - assets/vector-ouT.png
    - assets/vector-QiD.png
    - assets/rectangle-389-bg-frh.png
    - assets/vector-Vc5.png
    - assets/vector-MyB.png
    - assets/vector-ojF.png
    - assets/vector-C8H.png
    - assets/rectangle-389-bg-Jsj.png
    - assets/vector-Kb7.png
    - assets/vector-Mb7.png
    - assets/vector-Vq3.png
    - assets/vector-mPo.png
    - assets/rectangle-389-bg-ffw.png
    - assets/vector-znm.png
    - assets/vector-oAH.png
    - assets/vector-pQ9.png
    - assets/rectangle-388-bg-qPF.png
    - assets/vector-ji1.png
    - assets/vector-TQ5.png
    - assets/vector-CW5.png
    - assets/vector-ciV.png
    - assets/vector-EQH.png
    - assets/govt-kerala-1-removebg-preview.png
    - assets/images-1-TWy-removebg-preview.png

    #added by arutha
    - assets/icons/downArrow.png
    - assets/icons/fileIcon.png
    - assets/icons/homeIcon.png
    - assets/icons/plusIcon.png
    - assets/icons/component-1.png
    - assets/AdminIcons/homeIcon.png
    - assets/AdminIcons/dp.png
    - assets/AdminIcons/rightArrow.png
    - assets/Img/categories-bg.png
    - assets/images/AdminWelcomeImg.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

